services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
      - VERBOSE=true
      - API_KEY=${API_KEY} # Load from .env or your environment
      - API_KEY_NAME=x-api-key
      - CORS_ORIGINS=* # All cors allowed for development, change in production
    restart: unless-stopped
    # Optional: logs to console
    tty: true
